### ISSUE TITLE
Support for creating vertical slides

### ISSUE THREAD

**Issue by raducoravu** [stefan-jung/org.jung.reveal#1]
Based on Stefan Eike's idea when the DITA Map contains more than one level of topicrefs, the second level topic refs can appear as vertical slides.
A couple questions:

1) Should we add a parameter to control this behavior?
2) What happens to third, fourth,.... level topicrefs?

**Comment by stefan-jung** [comment]
1) Should we add a parameter to control this behavior?
This makes sense.

2) What happens to third, fourth,.... level topicrefs? 
I prefer to handle them as second level topic. Other ideas?

**Comment by raducoravu** [comment]
```
I prefer to handle them as second level topic. Other ideas?
```

Probably this would be the only possible option, Reveal JS does not seem to handle the case when in a vertical set of slides you create another section containing another vertical set of slides.

**Comment by stefan-jung** [comment]
To explain the problem roughly:

Reveal awaits is this structure

``` xml
<div class="reveal">
    <div class="slides">
        <section>Single Horizontal Slide</section>
        <section> <!-- This is another container --> 
            <section>Vertical Slide 1</section>
            <section>Vertical Slide 2</section>
        </section>
    </div>
</div>
```

But what we usually generate is:

``` xml
<div class="reveal">
    <div class="slides">
        <section>Single Horizontal Slide
            <section>Vertical Slide 1</section>
            <section>Vertical Slide 2</section>
        </section>
    </div>
</div>
```

**Comment by stefan-jung** [comment]
So, what the transformation does:

If the first level topic has children, inject a closing tag

``` xml
<div class="reveal">
    <div class="slides">
        <section>Single Horizontal Slide</section> <!-- New closing tag -->
            <section>Vertical Slide 1</section>
            <section>Vertical Slide 2</section>
        </section>
    </div>
</div>
```

If the second level is the first child, inject an opening tag:

``` xml
<div class="reveal">
    <div class="slides">
        <section>Single Horizontal Slide</section>
        <section> <!-- New opening tag -->
            <section>Vertical Slide 1</section>
            <section>Vertical Slide 2</section>
        </section>
    </div>
</div>
```

**Comment by stefan-jung** [comment]
Because you cannot inject either opening or closing tags with XSLT, you have to inject plain text.

**Comment by raducoravu** [comment]
I tried to find a solution without injecting tags as plain text, please see pull request.
